[Eth]
NetworkId =*
SyncMode ="fast"
NoPruning =false
NoPrefetch =false
LightPeers =100
UltraLightFraction =75
DatabaseCache =768
DatabaseFreezer = "<!--eth.databaseFreezer-->"
TrieCleanCache =256
TrieDirtyCache =256
TrieTimeout =3600000000000
EnablePreimageRecording =false
EWASMInterpreter = "<!--eth.EWASMInterpreter-->"
EVMInterpreter = "<!--eth.evmInterpreter-->"

[Eth.Miner]
GasFloor =4500000
GasCeil =4500000
GasPrice =0
Recommit =3000000000
Noverify =false
AllowedFutureBlockTime =5

[Eth.Ethash]
CacheDir = "ethash"
CachesInMem =2
CachesOnDisk =3
DatasetDir = "<!--eth.ethash.datasetDir-->"
DatasetsInMem =1
DatasetsOnDisk =2
PowMode =0

[Eth.TxPool]
Locals = []
NoLocals =false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit =1
PriceBump =10
AccountSlots =16
GlobalSlots =4096
AccountQueue =64
GlobalQueue =1024
Lifetime =10800000000000
TransactionSizeLimit =64
MaxCodeSize =24

[Eth.GPO]
Blocks =20
Percentile =60

[Eth.Istanbul]
RequestTimeout =5000
BlockPeriod =1
Epoch =30000
Ceil2Nby3Block = 0

[Shh]
MaxMessageSize = 1048576
MinimumAcceptedPOW = 2e-01
RestrictConnectionBetweenLightClients = true

[Node]
DataDir = "<!--node.dataDir-->"
omitempty = "<!--node.omitempty-->"
IPCPath = "geth.ipc"
HTTPPort = 22002
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["raft"]
WSPort = 8546
WSModules = ["raft"]
GraphQLPort = 8547
GraphQLVirtualHosts = ["localhost"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = []
BootstrapNodesV5 = []
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Dashboard]
Host = "localhost"
Port = 8080
Refresh = 5000000000